title: Urban Redevelopment Authority
title-abbreviated: URA
description: At URA, we adopt a long-term and comprehensive planning approach to formulate strategic plans such as the Concept Plan and the Master Plan to guide the physical development of Singapore in a sustainable manner.
url: https://www.ura.gov.sg
favicon: /images/favicon-URA-Logo.ico

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false
    # show breadcrumbs on root/home page
    image: false
    # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
# if i_want_to is true, there will be no key highlights
homepage_ideas-and-trends: true
homepage_resources: true
homepage_publications: true

# Feedback Form URL
feedback_form_url: "http://www.ura.gov.sg/feedbackWeb/contactus_feedback.jsp"

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

collections:
  who-we-are:
    output: true
  planning:
    output: true
  property:
    output: true
  guidelines:
    output: true
  carparks:
    output: true
  land-sales:
    output: true
  get-involved:
    output: true
  resources:
    output: true
  homepage_hero_i_want_to:
    output: true
  homepage_resources:
    output: true

# Isomer recommender system - only works for simple-page, leftnav-page, and post
recommender: true

exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
